spring:
  cloud:
    stream:
      function:
        # Define the supplier and the consumer to use by the order service
        definition: orderSupplier;productEventConsumer

      bindings:
        # Define the supplier as an output of the event
        orderSupplier-out-0:
          # Kafka topic or the channel destination name (Any name you want, needs to be meaningful)
          destination: order-event
        # Define the consumer as an input for the event
        productEventConsumer-in-0:
          # Kafka topic or the channel name to receive the event from (Any name you want, needs to be meaningful)
          destination: product-event
