server:
  port: 9999

spring:
  cloud:
    discovery:
      enabled: true

  application:
    name: API-Gateway

#eureka server location
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost