spring:
  cloud:
    stream:
      function:
        definition: orderEventProcessor
      bindings:
        orderEventProcessor-in-0:
          destination: order-event
        orderEventProcessor-out-0:
          destination: product-event
